version: "3.7"
services: 
  app:
    container_name: nuxt-container
    build: .
    volumes:
      - .:/app
    #   - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
    environment:
      HOST: 0.0.0.0
    working_dir: /app
    ports:
      - "3000:3000"
    command: sh -c "yarn install && yarn run dev"
    # command: ["yarn", "install", "&&", "yarn", "run", "dev"]
    # command: ["yarn", "run", "dev"]
    #   ["yarn", "install"]